# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# Copyright © 2013 by its contributors. See AUTHORS for details.
#

PROJECT = File.join(File.dirname(__FILE__))

Vagrant::Config.run do |config|
    config.vm.box     = "Ubuntu 12.04 (x86_64)"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.define "postgres" do |cfg|
        cfg.vm.forward_port 5432, 5432
        cfg.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = [
                File.join(PROJECT, 'cookbooks'),
            ]
            chef.add_recipe("apt")
            chef.add_recipe("build-essential")
            chef.add_recipe("postgresql::server")
            chef.json = {
                :postgresql => {
                    :version => "9.1",
                    :listen_addresses => "*",
                    :hba => [
                        { :method => "trust", :address => "0.0.0.0/0" },
                        { :method => "trust", :address => "::1/0" },
                    ],
                    :password => {
                        :postgres => "password"
                    }
                }
            }
        end
        cfg.vm.provision :shell, :path => '../etc/postgres/init.sh'
    end
end

#
# End of File
#
